import jsPDF from 'jspdf';
import JsBarcode from 'jsbarcode';
import { JobRecord } from '../types';

export const generateTravelerPdf = (job: JobRecord) => {
  // 1. Initialize Document
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // 2. Generate Barcode Image via Canvas
  const canvas = document.createElement('canvas');
  JsBarcode(canvas, job.jobId, {
    format: 'CODE128',
    width: 2.5,
    height: 60,
    displayValue: false, // We will draw the text manually in the PDF for cleaner scaling
    margin: 0,
  });
  const barcodeDataUrl = canvas.toDataURL('image/png');

  // 3. Document Header (AS9100D Formatting)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('DYNAMIC ENGINEERING - WIP TRAVELER', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('AS9100D / ISO 9001:2015 Production Routing Ticket', pageWidth / 2, 25, { align: 'center' });
  
  // 4. Inject Barcode
  // Center the barcode: assuming ~80mm width
  const barcodeWidth = 80;
  doc.addImage(barcodeDataUrl, 'PNG', (pageWidth - barcodeWidth) / 2, 35, barcodeWidth, 18);
  
  doc.setFont('courier', 'bold');
  doc.setFontSize(14);
  doc.text(job.jobId, pageWidth / 2, 58, { align: 'center' });

  // 5. Job Metadata Block
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(245, 248, 250);
  doc.rect(15, 65, pageWidth - 30, 40, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('ASSEMBLY / PART:', 20, 75);
  doc.text('REVISION:', 20, 85);
  doc.text('CUSTOMER:', 20, 95);
  
  doc.setFont('helvetica', 'normal');
  doc.text(job.assemblyName, 60, 75);
  doc.text(job.revision || 'N/A', 60, 85);
  doc.text(job.customer || 'Internal', 60, 95);

  const issueDate = new Date().toLocaleDateString('en-US');
  doc.setFont('helvetica', 'bold');
  doc.text('ISSUE DATE:', pageWidth - 70, 75);
  doc.text('QTY:', pageWidth - 70, 85);
  
  doc.setFont('helvetica', 'normal');
  doc.text(issueDate, pageWidth - 40, 75);
  doc.text('1 (Lot Tracking)', pageWidth - 40, 85);

  // 6. Routing Steps (Manual Sign-off Fallback)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('MANUFACTURING ROUTING SEQUENCE', 15, 120);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.text('* Electronic kiosk scan required at each gate. Physical sign-off is for QMS fallback only.', 15, 125);

  const stations = [
    { seq: 10, name: 'Assembly' },
    { seq: 20, name: 'AOI' },
    { seq: 30, name: 'Touchup' },
    { seq: 40, name: 'Test' },
    { seq: 50, name: 'Final AOI' },
    { seq: 60, name: 'QA (Final Inspect)' }
  ];

  let startY = 135;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);

  stations.forEach((station) => {
    // Row container
    doc.setDrawColor(150, 150, 150);
    doc.rect(15, startY, pageWidth - 30, 16);
    
    // Sequence Number Box
    doc.setFillColor(220, 230, 240);
    doc.rect(15, startY, 20, 16, 'FD');
    doc.text(station.seq.toString(), 25, startY + 10, { align: 'center' });

    // Station Name
    doc.text(station.name, 40, startY + 10);

    // Tech / Date fields
    doc.setFont('helvetica', 'normal');
    doc.text('Tech ID:', 110, startY + 10);
    doc.line(125, startY + 10, 155, startY + 10);
    
    doc.text('Date:', 160, startY + 10);
    doc.line(170, startY + 10, 190, startY + 10);
    
    doc.setFont('helvetica', 'bold');
    startY += 16;
  });

  // 7. Footer
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text(`Document auto-generated by Dynamic Engineering QMS. Asset ID: ${job.jobId}`, 15, 285);

  // Save the PDF directly in the browser
  doc.save(`Traveler_${job.jobId}.pdf`);
};